### ISSUE TITLE
This is awesome!

### ISSUE THREAD

**Issue by jsjoeio** [0x20F/bunny#1]
Hey!

I'm the author who write [the article](https://developers.facebook.com/blog/post/2020/06/03/build-smart-bookmarking-tool-rust-rocket/).

I found your crate by accident, but I have to say, I'm impressed! Your solution is waaaay more elegant than mine and I love the abstraction. I honestly my migrate from my [old solution](https://github.com/jsjoeio/rusty-bunny) over to yours because it seems easier to maintain 😅

Anyways, thanks so much for making this and putting it out there. You have no idea how happy this makes me! 

Cheers!

**Comment by 0x20F** [comment]
Hi!

Thank you! The odds of you finding it by accident, oh my god! 
I'm glad you like my take on it. You're welcome to do anything you want with it, it's your idea after all 😄
