### ISSUE TITLE
can't get it to work

### ISSUE THREAD

**Issue by paulgoodhew** [0x20F/bunny#4]
Hi I am ex-facebook and really miss this tool. 

I have followed the steps but get the following error:
------------------------------
$ bun
🔧 Configured for production.
    => address: 0.0.0.0
    => port: 8000
    => log: critical
    => workers: 16
    => secret key: generated
    => limits: forms = 32KiB
    => keep-alive: 5s
    => read timeout: 5s
    => write timeout: 5s
    => tls: disabled
Warning: environment is 'production', but no `secret_key` is configured
🚀 Rocket has launched from http://0.0.0.0:8000
Error: No matching routes for GET /?search=rd text/html.
Warning: Responding with 404 Not Found catcher.
Error: No matching routes for GET /?search=rd text/html.
Warning: Responding with 404 Not Found catcher.
-------------

Search engine is set to:[ ](http://0.0.0.0:8000?search=%s)

how can upload the bookmark.toml file to the root of 0.0.0.0:8000? I tried to ftp to it but it did not accept the request.

**Comment by 0x20F** [comment]
Hi!

Please make sure that:
- The `bookmark.toml` file is in your user's home directory, e.g `~/bookmarks.toml`
- You query the endpoint as follows: `/search?cmd=<your query here>`

It should work if setup like that. The docs could use a bit of work...

**Comment by paulgoodhew** [comment]
thanks this worked. This is such a great tool!
